### ISSUE TITLE
Unit tests should run in isolation

### ISSUE THREAD

**Issue by lochnesh** [vasisg/weather-app#2]
The unit tests for this project should run in isolation. For example, the unit tests should be executable without an internet connection.

Tests that require external dependencies should be marked as "integration tests" or "functional tests".

**Comment by vasisg** [comment]
Agree. The latest master branch has both unit and integrations tests. I have used nock npm module to mock the Openweathermap.org service. Now, the unit tests are run without connecting to internet. Also, the unit tests take less time compared to integration testing.
